name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '✨ Improvements'
    label: 'improvement'
  - title: '🐛 Hotfixes'
    labels:
      - 'bug'
      - 'bug fix'
  - title: '🔧 Maintenance'
    labels:
      - 'documentation'
      - 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  $CHANGES
